"""workflows executions notifications

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 18:11:59.903872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_notifications_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('workflow_definitions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.Enum('task.created', 'task.status_changed', 'schedule.cron', name='trigger_type'), nullable=False),
    sa.Column('trigger_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workflow_definitions_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_definitions_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definitions'))
    )
    op.create_index('ix_workflow_definitions_org_trigger', 'workflow_definitions', ['org_id', 'trigger_type'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('steps_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], name=op.f('fk_workflow_executions_definition_id_workflow_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_executions_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_executions'))
    )
    op.create_index('ix_workflow_executions_active', 'workflow_executions', ['status'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('ix_workflow_executions_definition_status', 'workflow_executions', ['definition_id', 'status'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('create_task', 'update_field', 'send_notification', 'call_webhook', 'delay', name='step_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], name=op.f('fk_workflow_steps_definition_id_workflow_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps')),
    sa.UniqueConstraint('definition_id', 'position', name=op.f('uq_workflow_steps_definition_id'))
    )
    op.create_table('step_runs',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('create_task', 'update_field', 'send_notification', 'call_webhook', 'delay', name='step_type'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name=op.f('fk_step_runs_execution_id_workflow_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step_runs')),
    sa.UniqueConstraint('execution_id', 'position', 'attempt', name=op.f('uq_step_runs_execution_id'))
    )
    op.create_index('uq_step_runs_one_success', 'step_runs', ['execution_id', 'position'], unique=True, postgresql_where=sa.text("status = 'succeeded'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_step_runs_one_success', table_name='step_runs', postgresql_where=sa.text("status = 'succeeded'"))
    op.drop_table('step_runs')
    op.drop_table('workflow_steps')
    op.drop_index('ix_workflow_executions_definition_status', table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_active', table_name='workflow_executions', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('workflow_executions')
    op.drop_index('ix_workflow_definitions_org_trigger', table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index('ix_notifications_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_table('notifications')
    for enum_name in ('execution_status', 'step_type', 'trigger_type'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
